name: Rebase
on:
  workflow_dispatch:
  schedule:
    - cron: '42 0 * * *'
jobs:
  example:
    name: Rebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libudev-dev
          git config --global user.name "username"
          git config --global user.email "username@users.noreply.github.com"
      - name: Run Rebase
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        run: |
          source ssh-deploy-key
          ./run-all
